namespace CodeFiCS.Metadata
{
    static class Metadata_Assembly_CSharp
    {
        private static readonly string[] ProjectFiles = {"0019FEHBKODMJGBCIJIFIBDALLMHCNELLLKE","MGKIEIKNCNBCGEPDFGFCDIPMAMJLIPLG","001AHMOHJBDLNCLFCBFMHKAFAKMKDDLHOCED","FMFODNPLBJGOLNONBHOFLAKNONIGIHDH","0016OPBBGFMNAMFIGIFGFBKOCMNJEAGKFBAC","OLPNIHGDCPOCLKFFNKFCHKJCOKDENKDM","0021ECJIJGPJPNKFFICEPFOCBIEBFLNCAACL","HLMAFOIDEJGJAHIMHPDEEGGNPCFHBECC","0021GJECMOLJCIGKAOHKNPJJFPODCFGMOAOP","CEFBNAOGOEGOOJPOFGAEPELKCKIMGPML","0019NJJCPBPJLHBIONAPLCHFOPGOHBJLNAPA","PGBBPNIKLLLNLDLIPOOBKECOGAHAAEIM","0022OBEHPOCAGMMEKGKJKNLPIMDNHJPFNPJO","PMCJFIACBABNGGCKLANOJAIPJPMOLJCO","0016NCCJHMOPANDJOBKKHAEGNNJBCGMOKPHA","PJMPJDEEKNBKHKIJDOCMHBBCBIGIKCOH","0024BKECEJCPPKEOEIMGHPDIBEKEIBLBOKJN","HNEBJHEGJJDOCCGNICKBPIGFKCCNGGIP","0020LJGGPIDKCHPCCMODBKPBHFGELHNPBHEO","GLNFEKDAMKMONJPLACMCAHMKDOBJDKCA","0011EHHMLBFCBJFMNFHBNJMHOLDIEHLPPLIH","GNIGOMJPFJCOCCOANOKMCLEJJKEOGCEM"};
        private static readonly string[] Defines = {};
    }
}