namespace CodeFiCS.Metadata
{
    static class Metadata_Assembly_CSharp
    {
        private static readonly string[] ProjectFiles = {"0019FEHBKODMJGBCIJIFIBDALLMHCNELLLKE","MGKIEIKNCNBCGEPDFGFCDIPMAMJLIPLG","001AHMOHJBDLNCLFCBFMHKAFAKMKDDLHOCED","FMFODNPLBJGOLNONBHOFLAKNONIGIHDH","001ALKPFLHGEEIIBEJLEDNJDEKOLFOBCPMAA","PPLNBADGDKODDNDDLBPPDKKACDGPGDKL","0016OPBBGFMNAMFIGIFGFBKOCMNJEAGKFBAC","OLPNIHGDCPOCLKFFNKFCHKJCOKDENKDM","0017BKDEINJFDEHAENJAAJAPDMKGAEBLNGDL","CDBMADDNGKHJHCPCNLPPGBGMEMGEKLFK","0020LJGGPIDKCHPCCMODBKPBHFGELHNPBHEO","GLNFEKDAMKMONJPLACMCAHMKDOBJDKCA","001DHPANPPHNENEIAFIMDNBJHIAELJAPHNBP","IANEAFDDDPDAGBHKOKOPDCFLFFNPMFDD","0021ECJIJGPJPNKFFICEPFOCBIEBFLNCAACL","HLMAFOIDEJGJAHIMHPDEEGGNPCFHBECC","0021GJECMOLJCIGKAOHKNPJJFPODCFGMOAOP","CEFBNAOGOEGOOJPOFGAEPELKCKIMGPML","0019NJJCPBPJLHBIONAPLCHFOPGOHBJLNAPA","GPENCGLMLAFIGEPNHDOBOBICENOGMAFP","0022OBEHPOCAGMMEKGKJKNLPIMDNHJPFNPJO","PMCJFIACBABNGGCKLANOJAIPJPMOLJCO","0016NCCJHMOPANDJOBKKHAEGNNJBCGMOKPHA","PJMPJDEEKNBKHKIJDOCMHBBCBIGIKCOH","0024BKECEJCPPKEOEIMGHPDIBEKEIBLBOKJN","HNEBJHEGJJDOCCGNICKBPIGFKCCNGGIP","0015GIINJLMNMMHFKLEHLNGPIHGKFIPFHEKF","HMEIKIDCANAOBHGIEDFEFPBKBHPDLBGJ","0011EHHMLBFCBJFMNFHBNJMHOLDIEHLPPLIH","KMAILAIOFCELPBHFJJONJCOCCPMEIIEL"};
        private static readonly string[] Defines = {};
    }
}