namespace CodeFiCS.Metadata
{
    static class Metadata_Assembly_CSharp
    {
        private static readonly string[] ProjectFiles = {"0019FEHBKODMJGBCIJIFIBDALLMHCNELLLKE","MGKIEIKNCNBCGEPDFGFCDIPMAMJLIPLG","001AHMOHJBDLNCLFCBFMHKAFAKMKDDLHOCED","FMFODNPLBJGOLNONBHOFLAKNONIGIHDH","001ALKPFLHGEEIIBEJLEDNJDEKOLFOBCPMAA","PPLNBADGDKODDNDDLBPPDKKACDGPGDKL","0016OPBBGFMNAMFIGIFGFBKOCMNJEAGKFBAC","OLPNIHGDCPOCLKFFNKFCHKJCOKDENKDM","0017BKDEINJFDEHAENJAAJAPDMKGAEBLNGDL","CDBMADDNGKHJHCPCNLPPGBGMEMGEKLFK","0020LJGGPIDKCHPCCMODBKPBHFGELHNPBHEO","GLNFEKDAMKMONJPLACMCAHMKDOBJDKCA","001DHPANPPHNENEIAFIMDNBJHIAELJAPHNBP","IANEAFDDDPDAGBHKOKOPDCFLFFNPMFDD","0021ECJIJGPJPNKFFICEPFOCBIEBFLNCAACL","HLMAFOIDEJGJAHIMHPDEEGGNPCFHBECC","0016NCCJHMOPANDJOBKKHAEGNNJBCGMOKPHA","PJMPJDEEKNBKHKIJDOCMHBBCBIGIKCOH","0015GIINJLMNMMHFKLEHLNGPIHGKFIPFHEKF","HMEIKIDCANAOBHGIEDFEFPBKBHPDLBGJ","0011EHHMLBFCBJFMNFHBNJMHOLDIEHLPPLIH","EJOGHPMCFBALBILBMLOMADLDMPOEMKLJ"};
        private static readonly string[] Defines = {};
    }
}